// hotelmanagement-vue/src/views/dashboard/HotelCreate.vue
<template>
      <div class="container">
        <h1 class="h3 mb-3 fw-normal">Create New Hotel</h1>
        <div class="form-floating">
            <input v-model="hotelCreateFormData.name" type="text" class="form-control form-control-top"/>
            <label for="floatingInput">Name</label>
        </div>
        <div class="form-floating">
            <input v-model="hotelCreateFormData.description" type="text" class="form-control form-control-bottom"/>
            <label for="floatingInput">Description</label>
        </div>
        <div class="checkbox mb-3">
        <!-- <label>
            <input type="checkbox" value="remember-me"> Remember me
        </label> -->
        </div>
        <button class="w-100 btn btn-lg btn-primary" @click="handleCreateHotel()">Create Hotel</button>
    </div>
</template>

<script lang="ts">
import type { IHotel } from "@/domain/IHotel";
import HotelService from "@/services/HotelService";
import { useHotelStore } from "@/stores/Hotel";
import { Vue } from "vue-class-component";

export default class HotelCreate extends Vue {
    hotelStore = useHotelStore();

    hotelCreateFormData: IHotel = {
        name: "",
        description: ""
    }

    async handleCreateHotel() {
        await HotelService.post(this.hotelCreateFormData)
            .then((res) => {
                if (!res.success) {
                    console.log(res)
                    return;
                }
                this.hotelStore.addHotel(res.data!);
                this.$router.push(`/dashboard/${res.data?.id}`);
            }
            ).catch((res) => {
                console.log(res);
            }
        );
    }
}
</script>

<style>

</style>

// hotelmanagement-react/src/views/dashboard/HotelCreate.tsx
import React, { useContext, useState } from "react";
import { useNavigate } from "react-router";
import { IHotel } from "../../domain/IHotel";
import HotelService from "../../services/HotelService";
import { AppContext } from "../../state/AppContext";

const HotelCreate = () => {
    const navigate = useNavigate();
    const appState = useContext(AppContext);

    const [name, setName] = useState("")
    const [descripton, setDescription] = useState("")

    const handleSubmitHotel = async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        let hotel: IHotel = {
            name: name,
            description: descripton
        }
        
        let res = await HotelService.post(hotel);

        if (res.data != null) {
            appState.setHotels(appState.hotels.concat(res.data));
            navigate(`../${res.data.id!}`)
        }
    }

    return(
        <>
            <div className="container">
                <form onSubmit={handleSubmitHotel}>
                    <h1 className="h3 mb-3 fw-normal">Create New Hotel</h1>
                    <div className="form-floating">
                        <input type="text" className="form-control form-control-top"
                        onChange={(e) => {setName(e.target.value)}}/>
                        <label>Name</label>
                    </div>
                    <div className="form-floating">
                        <input type="text" className="form-control form-control-bottom"
                        onChange={(e) => {setDescription(e.target.value)}}/>
                        <label>Description</label>
                    </div>
                    <button className="w-100 btn btn-lg btn-primary">Create Hotel</button>
                </form>
            </div>
        </>
    )
}

export default HotelCreate;
