// hotelmanagement-vue/src/views/Home.vue
<template>
    <div class="container">
        <div class="px-4 py-5 my-5 text-center">
            <h1 class="display-5 fw-bold">Hotel!</h1>
            <div class="col-lg-6 mx-auto">
                <p class="lead mb-4">Hotel management landing page</p>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                    <template v-if="identityStore.$state.data == null">
                        <RouterLink to="/login">
                            <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Login</button>
                        </RouterLink>
                        <RouterLink to="/register">
                            <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Register</button>
                        </RouterLink>
                    </template>
                    <template v-else>
                        <button type="button" class="btn btn-primary btn-lg px-4 gap-3" @click="handleLogOut()">Logout</button>
                        <RouterLink to="/dashboard">
                            <button type="button" class="btn btn-primary btn-lg px-4 gap-3">To Dashboard</button>
                        </RouterLink>
                    </template>
                </div>
            </div>
        </div>
        <RouterView />
    </div>
</template>

<script lang="ts">
import IdentityService from "@/services/IdentityService";
import { useIdentityStore } from "@/stores/Identity";
import { Vue } from "vue-class-component";
export default class Home extends Vue {
    identityStore = useIdentityStore();
    
    handleLogOut() {
        IdentityService.logout()
    }
}
</script>

<style>
.form-identity {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
}
</style>

// hotelmanagement-react/src/views/Home.tsx
import React, { useContext } from "react";
import { Routes, Route } from "react-router";
import { Link } from "react-router-dom";
import LoginForm from "../components/LoginForm";
import RegisterForm from "../components/RegisterForm";
import IdentityService from "../services/IdentityService";
import { AppContext } from "../state/AppContext";

const Home = () => {
    const appState = useContext(AppContext);
    
    const handleLogout = () => {
        IdentityService.logout();
        appState.setloggedIn(false);
    }

    const NavButtons = () => {
        if (IdentityService.loggedIn()) {
            return (
                <>
                <button type="button" className="btn btn-primary btn-lg px-4 gap-3"
                onClick={handleLogout}>
                    Logout
                    </button>
                <Link to="/dashboard">
                    <button type="button" className="btn btn-primary btn-lg px-4 gap-3">To Dashboard</button>
                </Link>
                </>
            )
        }
        return (
            <>
            <Link to="/login">
            <button type="button" className="btn btn-primary btn-lg px-4 gap-3">Login</button>
            </Link>
            <Link to="/register">
                <button type="button" className="btn btn-primary btn-lg px-4 gap-3">Register</button>
            </Link>
            </>
        )
    }

    return(
        <>
        <div className="container">
            <div className="px-4 py-5 my-5 text-center">
                <h1 className="display-5 fw-bold">Hotel!</h1>
                <div className="col-lg-6 mx-auto">
                    <p className="lead mb-4">Hotel management landing page</p>
                    <div className="d-grid gap-2 d-sm-flex justify-content-sm-center">
                        {NavButtons()}
                    </div>
                </div>
            </div>
            <Routes>
                <Route path="login" element={ <LoginForm /> } />
                <Route path="register" element={ <RegisterForm />} />
            </Routes>
        </div>
        </>
    )
}

export default Home;
